In [6]:
import glob
from PIL import Image
import numpy as np
import pandas as pd

def load_img(imfile):
    img = Image.open(imfile)
    img.load()
    return np.asarray(img, dtype="int32")

#read files
host_dir = "kaggle/cell_images/"
uninfected = glob.glob(host_dir + "Uninfected/*.png")
parasitized = glob.glob(host_dir + "Parasitized/*.png")

#extend previous code to get the colors in each image
pNColors = np.zeros(len(uninfected))
uNColors = np.zeros(len(parasitized))

i = load_img(parasitized[0])
ishp = i.shape
p_df = pd.DataFrame(i.reshape(ishp[0]*ishp[1],3)).drop_duplicates()
i = load_img(uninfected[0])
ishp = i.shape
u_df = pd.DataFrame(i.reshape(ishp[0]*ishp[1],3)).drop_duplicates()

pdfs = []
udfs = []
for dex, im in enumerate(parasitized):
    i = load_img(im)
    ishp = i.shape
    df = pd.DataFrame(i.reshape(ishp[0]*ishp[1],3))#.drop_duplicates()
    #p_df = pd.concat([p_df, df])
    pdfs.append(df)
    pNColors[dex] = len(df.index)#gets # of colors in image
#pColors = p_df.drop_duplicates().to_numpy()

for dex, im in enumerate(uninfected):
    i = load_img(im)
    ishp = i.shape
    df = pd.DataFrame(i.reshape(ishp[0]*ishp[1],3))#.drop_duplicates()
    #u_df = pd.concat([u_df, df])
    udfs.append(df)
    uNColors[dex] = len(df.index)#gets # of colors in image
#uColors = u_df.drop_duplicate().to_numpy()
#u_df = np.concatenate(([el.drop_duplicates().to_numpy() for el in udfs]))
#p_df = np.concatenate(([el.drop_duplicates().to_numpy() for el in pdfs]))
u_df = np.concatenate(([el.to_numpy() for el in udfs]))
p_df = np.concatenate(([el.to_numpy() for el in pdfs]))
allColors = np.concatenate(([u_df,p_df]))
print(allColors.shape)

(491517774, 3)


In [ ]:
allColors = pd.DataFrame(allColors).drop_duplicates().to_numpy()
print(allColors.shape)
allColors = np.unique(allColors, axis=1)
print(allColors.shape)

In [7]:
cra = allColors[:,0]
cga = allColors[:,1]
cba = allColors[:,2]
indices = np.where(cra==226)#gets just locatins of the red
sublistColors = np.take(cga, indices)
indices = np.take(indices, np.where(sublistColors[0]==176))#matches now both red and green
sublistColors = np.take(cba, indices)
indices

array([[    44877,     51096,     51169, ..., 491279971, 491374076,
        491500992]])

In [11]:
allColors[51169]

array([226, 176, 167], dtype=int32)

In [9]:
dex = np.take(indices, np.where(sublistColors[0]==167))[0][0]#matches all 3 colors

In [10]:
dex

51169

In [12]:
test = pd.DataFrame(allColors).drop_duplicates().to_numpy()

In [13]:
test.shape

(366057, 3)

In [16]:
crat = test[:,0]
cgat = test[:,1]
cbat = test[:,2]
indices = np.where(crat==226)#gets just locatins of the red
sublistColors = np.take(cgat, indices)
indices = np.take(indices, np.where(sublistColors[0]==176))#matches now both red and green
sublistColors = np.take(cbat, indices)
indices
dex = np.take(indices, np.where(sublistColors[0]==167))[0][0]#matches all 3 colors

In [17]:
dex

376

In [18]:
test[376]

array([226, 176, 167], dtype=int32)

In [19]:
np.save(host_dir + "images_allColors.npy", test)

In [20]:
allColors = np.load(host_dir + "images_allColors.npy")

In [23]:
allColors.shape

(366057, 3)

In [24]:
allColors[376]

array([226, 176, 167], dtype=int32)