In [1]:
#let's take another run on keras

In [2]:
from keras.models import Sequential
from keras import layers


Using Theano backend.


In [6]:
import numpy as np
from keras.callbacks import EarlyStopping

In [4]:
host_dir = "kaggle/cell_images/"
uninfected = np.loadtxt(host_dir + "uninfected_nColors.txt")
parasitized = np.loadtxt(host_dir + "parasitized_nColors.txt")
labels = np.concatenate([np.zeros(13779), np.ones(13779)])
data = np.concatenate([uninfected, parasitized])

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.3, random_state=42)

In [24]:
input_dim = 1  # Number of features

model = Sequential()
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(2, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 10)                20        
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 22        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [23]:
early_stopping_monitor = EarlyStopping(patience=5)

In [25]:
model.fit(x_train, y_train, batch_size=10, validation_split=0.2, callbacks=[early_stopping_monitor], epochs=100)

INFO (theano.gof.compilelock): Refreshing lock /home/brandon/.theano/compiledir_Linux-4.4--Microsoft-x86_64-with-debian-buster-sid-x86_64-3.7.3-64/lock_dir/lock


Train on 15432 samples, validate on 3858 samples
Epoch 1/100
15432/15432 [==============================] - 1s 83us/step - loss: 5.8523 - acc: 0.5356 - val_loss: 0.8333 - val_acc: 0.4964
Epoch 2/100
15432/15432 [==============================] - 1s 86us/step - loss: 0.7905 - acc: 0.6959 - val_loss: 0.5339 - val_acc: 0.7374
Epoch 3/100
15432/15432 [==============================] - 2s 98us/step - loss: 0.7750 - acc: 0.7129 - val_loss: 1.0248 - val_acc: 0.7460
Epoch 4/100
15432/15432 [==============================] - 1s 85us/step - loss: 0.7821 - acc: 0.7168 - val_loss: 0.5916 - val_acc: 0.6659
Epoch 5/100
15432/15432 [==============================] - 1s 88us/step - loss: 0.7615 - acc: 0.7168 - val_loss: 0.5719 - val_acc: 0.6882
Epoch 6/100
15432/15432 [==============================] - 1s 92us/step - loss: 0.7699 - acc: 0.7200 - val_loss: 0.5769 - val_acc: 0.6814
Epoch 7/100
15432/15432 [==============================] - 1s 89us/step - loss: 0.7511 - acc: 0.7221 - val_loss: 0.5807 - v

In [9]:
y_train

array([1., 0., 0., ..., 0., 1., 1.])

In [18]:
x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.3, random_state=42)
y_train = np.column_stack((y_train, 1-y_train))
y_test = np.column_stack((y_test, 1-y_test))

In [19]:
y_train

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [20]:
x_train

array([2137.,  171.,  795., ...,  314., 1682., 2200.])

In [26]:
model = Sequential()
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(2, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=10, validation_split=0.2, callbacks=[early_stopping_monitor], epochs=100)

INFO (theano.gof.compilelock): Refreshing lock /home/brandon/.theano/compiledir_Linux-4.4--Microsoft-x86_64-with-debian-buster-sid-x86_64-3.7.3-64/lock_dir/lock


Train on 15432 samples, validate on 3858 samples
Epoch 1/100
15432/15432 [==============================] - 1s 88us/step - loss: 1.0305 - acc: 0.6406 - val_loss: 0.7706 - val_acc: 0.5399
Epoch 2/100
15432/15432 [==============================] - 1s 90us/step - loss: 0.8350 - acc: 0.7076 - val_loss: 1.7773 - val_acc: 0.6514
Epoch 3/100
15432/15432 [==============================] - 2s 102us/step - loss: 0.9984 - acc: 0.6995 - val_loss: 0.5722 - val_acc: 0.7644
Epoch 4/100
15432/15432 [==============================] - 1s 95us/step - loss: 0.8175 - acc: 0.7118 - val_loss: 1.0211 - val_acc: 0.7561
Epoch 5/100
15432/15432 [==============================] - 1s 96us/step - loss: 0.8237 - acc: 0.7105 - val_loss: 1.4743 - val_acc: 0.6998
Epoch 6/100
15432/15432 [==============================] - 1s 95us/step - loss: 0.8013 - acc: 0.7172 - val_loss: 0.5661 - val_acc: 0.7755
Epoch 7/100
15432/15432 [==============================] - 1s 91us/step - loss: 0.7135 - acc: 0.7205 - val_loss: 0.5479 - 

In [27]:
model = Sequential()
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(2, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=10, validation_split=0.2, callbacks=[early_stopping_monitor], epochs=100)

Train on 15432 samples, validate on 3858 samples
Epoch 1/100
15432/15432 [==============================] - 1s 95us/step - loss: 1.0134 - acc: 0.6453 - val_loss: 0.5305 - val_acc: 0.7525
Epoch 2/100
15432/15432 [==============================] - 2s 101us/step - loss: 0.8718 - acc: 0.7035 - val_loss: 0.8168 - val_acc: 0.7880
Epoch 3/100
15432/15432 [==============================] - 2s 97us/step - loss: 0.8913 - acc: 0.7039 - val_loss: 0.5619 - val_acc: 0.7102
Epoch 4/100
15432/15432 [==============================] - 2s 106us/step - loss: 0.7917 - acc: 0.7166 - val_loss: 1.1236 - val_acc: 0.7390
Epoch 5/100
15432/15432 [==============================] - 2s 101us/step - loss: 0.7618 - acc: 0.7171 - val_loss: 0.8429 - val_acc: 0.7732
Epoch 6/100
15432/15432 [==============================] - 2s 100us/step - loss: 0.6828 - acc: 0.7249 - val_loss: 0.9912 - val_acc: 0.7411


In [28]:
model = Sequential()
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(2, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=10, validation_split=0.2, callbacks=[early_stopping_monitor], epochs=100)

Train on 15432 samples, validate on 3858 samples
Epoch 1/100
15432/15432 [==============================] - 2s 103us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 2/100
15432/15432 [==============================] - 2s 107us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 3/100
15432/15432 [==============================] - 2s 106us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 4/100
15432/15432 [==============================] - 2s 114us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 5/100
15432/15432 [==============================] - 2s 106us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 6/100
15432/15432 [==============================] - 2s 106us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961


In [29]:
model = Sequential()
model.add(layers.Dense(100, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(2, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=10, validation_split=0.2, callbacks=[early_stopping_monitor], epochs=100)

INFO (theano.gof.compilelock): Refreshing lock /home/brandon/.theano/compiledir_Linux-4.4--Microsoft-x86_64-with-debian-buster-sid-x86_64-3.7.3-64/lock_dir/lock


Train on 15432 samples, validate on 3858 samples
Epoch 1/100
15432/15432 [==============================] - 1s 87us/step - loss: 8.0182 - acc: 0.4998 - val_loss: 7.9528 - val_acc: 0.5039
Epoch 2/100
15432/15432 [==============================] - 1s 92us/step - loss: 8.0182 - acc: 0.4998 - val_loss: 7.9528 - val_acc: 0.5039
Epoch 3/100
15432/15432 [==============================] - 1s 95us/step - loss: 8.0182 - acc: 0.4998 - val_loss: 7.9528 - val_acc: 0.5039
Epoch 4/100
15432/15432 [==============================] - 1s 94us/step - loss: 8.0182 - acc: 0.4998 - val_loss: 7.9528 - val_acc: 0.5039
Epoch 5/100
15432/15432 [==============================] - 2s 97us/step - loss: 8.0182 - acc: 0.4998 - val_loss: 7.9528 - val_acc: 0.5039
Epoch 6/100
15432/15432 [==============================] - 1s 95us/step - loss: 8.0182 - acc: 0.4998 - val_loss: 7.9528 - val_acc: 0.5039


In [30]:
model = Sequential()
model.add(layers.Dense(100, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(100, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(100, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(2, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=10, validation_split=0.2, callbacks=[early_stopping_monitor], epochs=100)

Train on 15432 samples, validate on 3858 samples
Epoch 1/100
15432/15432 [==============================] - 3s 225us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 2/100
15432/15432 [==============================] - 4s 247us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 3/100
15432/15432 [==============================] - 4s 257us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 4/100
15432/15432 [==============================] - 4s 241us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 5/100
15432/15432 [==============================] - 4s 241us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 6/100
15432/15432 [==============================] - 4s 247us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961


In [32]:
model = Sequential()
model.add(layers.Dense(100, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(100, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(100, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(2, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=5, validation_split=0.2, callbacks=[early_stopping_monitor], epochs=100)

Train on 15432 samples, validate on 3858 samples
Epoch 1/100
15432/15432 [==============================] - 7s 446us/step - loss: 8.0079 - acc: 0.4999 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 2/100
15432/15432 [==============================] - 8s 507us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 3/100
15432/15432 [==============================] - 8s 494us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 4/100
15432/15432 [==============================] - 8s 529us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 5/100
15432/15432 [==============================] - 8s 529us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 6/100
15432/15432 [==============================] - 8s 523us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
