In [1]:
#let's take another run on keras

In [1]:
from keras.models import Sequential
from keras import layers


Using TensorFlow backend.


In [5]:
import numpy as np
from keras.callbacks import EarlyStopping

Using TensorFlow backend.


In [6]:
host_dir = "./"
uninfected = np.loadtxt(host_dir + "uninfected_nColors.txt")
parasitized = np.loadtxt(host_dir + "parasitized_nColors.txt")
labels = np.concatenate([np.zeros(13779), np.ones(13779)])
data = np.concatenate([uninfected, parasitized])

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.3, random_state=42)

In [24]:
input_dim = 1  # Number of features

model = Sequential()
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(2, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 10)                20        
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 22        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [23]:
early_stopping_monitor = EarlyStopping(patience=5)

In [25]:
model.fit(x_train, y_train, batch_size=10, validation_split=0.2, callbacks=[early_stopping_monitor], epochs=100)

INFO (theano.gof.compilelock): Refreshing lock /home/brandon/.theano/compiledir_Linux-4.4--Microsoft-x86_64-with-debian-buster-sid-x86_64-3.7.3-64/lock_dir/lock


Train on 15432 samples, validate on 3858 samples
Epoch 1/100
15432/15432 [==============================] - 1s 83us/step - loss: 5.8523 - acc: 0.5356 - val_loss: 0.8333 - val_acc: 0.4964
Epoch 2/100
15432/15432 [==============================] - 1s 86us/step - loss: 0.7905 - acc: 0.6959 - val_loss: 0.5339 - val_acc: 0.7374
Epoch 3/100
15432/15432 [==============================] - 2s 98us/step - loss: 0.7750 - acc: 0.7129 - val_loss: 1.0248 - val_acc: 0.7460
Epoch 4/100
15432/15432 [==============================] - 1s 85us/step - loss: 0.7821 - acc: 0.7168 - val_loss: 0.5916 - val_acc: 0.6659
Epoch 5/100
15432/15432 [==============================] - 1s 88us/step - loss: 0.7615 - acc: 0.7168 - val_loss: 0.5719 - val_acc: 0.6882
Epoch 6/100
15432/15432 [==============================] - 1s 92us/step - loss: 0.7699 - acc: 0.7200 - val_loss: 0.5769 - val_acc: 0.6814
Epoch 7/100
15432/15432 [==============================] - 1s 89us/step - loss: 0.7511 - acc: 0.7221 - val_loss: 0.5807 - v

In [9]:
y_train

array([1., 0., 0., ..., 0., 1., 1.])

In [18]:
x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.3, random_state=42)
y_train = np.column_stack((y_train, 1-y_train))
y_test = np.column_stack((y_test, 1-y_test))

In [19]:
y_train

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [20]:
x_train

array([2137.,  171.,  795., ...,  314., 1682., 2200.])

In [26]:
model = Sequential()
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(2, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=10, validation_split=0.2, callbacks=[early_stopping_monitor], epochs=100)

INFO (theano.gof.compilelock): Refreshing lock /home/brandon/.theano/compiledir_Linux-4.4--Microsoft-x86_64-with-debian-buster-sid-x86_64-3.7.3-64/lock_dir/lock


Train on 15432 samples, validate on 3858 samples
Epoch 1/100
15432/15432 [==============================] - 1s 88us/step - loss: 1.0305 - acc: 0.6406 - val_loss: 0.7706 - val_acc: 0.5399
Epoch 2/100
15432/15432 [==============================] - 1s 90us/step - loss: 0.8350 - acc: 0.7076 - val_loss: 1.7773 - val_acc: 0.6514
Epoch 3/100
15432/15432 [==============================] - 2s 102us/step - loss: 0.9984 - acc: 0.6995 - val_loss: 0.5722 - val_acc: 0.7644
Epoch 4/100
15432/15432 [==============================] - 1s 95us/step - loss: 0.8175 - acc: 0.7118 - val_loss: 1.0211 - val_acc: 0.7561
Epoch 5/100
15432/15432 [==============================] - 1s 96us/step - loss: 0.8237 - acc: 0.7105 - val_loss: 1.4743 - val_acc: 0.6998
Epoch 6/100
15432/15432 [==============================] - 1s 95us/step - loss: 0.8013 - acc: 0.7172 - val_loss: 0.5661 - val_acc: 0.7755
Epoch 7/100
15432/15432 [==============================] - 1s 91us/step - loss: 0.7135 - acc: 0.7205 - val_loss: 0.5479 - 

In [27]:
model = Sequential()
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(2, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=10, validation_split=0.2, callbacks=[early_stopping_monitor], epochs=100)

Train on 15432 samples, validate on 3858 samples
Epoch 1/100
15432/15432 [==============================] - 1s 95us/step - loss: 1.0134 - acc: 0.6453 - val_loss: 0.5305 - val_acc: 0.7525
Epoch 2/100
15432/15432 [==============================] - 2s 101us/step - loss: 0.8718 - acc: 0.7035 - val_loss: 0.8168 - val_acc: 0.7880
Epoch 3/100
15432/15432 [==============================] - 2s 97us/step - loss: 0.8913 - acc: 0.7039 - val_loss: 0.5619 - val_acc: 0.7102
Epoch 4/100
15432/15432 [==============================] - 2s 106us/step - loss: 0.7917 - acc: 0.7166 - val_loss: 1.1236 - val_acc: 0.7390
Epoch 5/100
15432/15432 [==============================] - 2s 101us/step - loss: 0.7618 - acc: 0.7171 - val_loss: 0.8429 - val_acc: 0.7732
Epoch 6/100
15432/15432 [==============================] - 2s 100us/step - loss: 0.6828 - acc: 0.7249 - val_loss: 0.9912 - val_acc: 0.7411


In [28]:
model = Sequential()
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(2, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=10, validation_split=0.2, callbacks=[early_stopping_monitor], epochs=100)

Train on 15432 samples, validate on 3858 samples
Epoch 1/100
15432/15432 [==============================] - 2s 103us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 2/100
15432/15432 [==============================] - 2s 107us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 3/100
15432/15432 [==============================] - 2s 106us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 4/100
15432/15432 [==============================] - 2s 114us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 5/100
15432/15432 [==============================] - 2s 106us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 6/100
15432/15432 [==============================] - 2s 106us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961


In [29]:
model = Sequential()
model.add(layers.Dense(100, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(2, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=10, validation_split=0.2, callbacks=[early_stopping_monitor], epochs=100)

INFO (theano.gof.compilelock): Refreshing lock /home/brandon/.theano/compiledir_Linux-4.4--Microsoft-x86_64-with-debian-buster-sid-x86_64-3.7.3-64/lock_dir/lock


Train on 15432 samples, validate on 3858 samples
Epoch 1/100
15432/15432 [==============================] - 1s 87us/step - loss: 8.0182 - acc: 0.4998 - val_loss: 7.9528 - val_acc: 0.5039
Epoch 2/100
15432/15432 [==============================] - 1s 92us/step - loss: 8.0182 - acc: 0.4998 - val_loss: 7.9528 - val_acc: 0.5039
Epoch 3/100
15432/15432 [==============================] - 1s 95us/step - loss: 8.0182 - acc: 0.4998 - val_loss: 7.9528 - val_acc: 0.5039
Epoch 4/100
15432/15432 [==============================] - 1s 94us/step - loss: 8.0182 - acc: 0.4998 - val_loss: 7.9528 - val_acc: 0.5039
Epoch 5/100
15432/15432 [==============================] - 2s 97us/step - loss: 8.0182 - acc: 0.4998 - val_loss: 7.9528 - val_acc: 0.5039
Epoch 6/100
15432/15432 [==============================] - 1s 95us/step - loss: 8.0182 - acc: 0.4998 - val_loss: 7.9528 - val_acc: 0.5039


In [30]:
model = Sequential()
model.add(layers.Dense(100, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(100, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(100, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(2, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=10, validation_split=0.2, callbacks=[early_stopping_monitor], epochs=100)

Train on 15432 samples, validate on 3858 samples
Epoch 1/100
15432/15432 [==============================] - 3s 225us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 2/100
15432/15432 [==============================] - 4s 247us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 3/100
15432/15432 [==============================] - 4s 257us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 4/100
15432/15432 [==============================] - 4s 241us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 5/100
15432/15432 [==============================] - 4s 241us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 6/100
15432/15432 [==============================] - 4s 247us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961


In [32]:
model = Sequential()
model.add(layers.Dense(100, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(100, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(100, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(2, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=5, validation_split=0.2, callbacks=[early_stopping_monitor], epochs=100)

Train on 15432 samples, validate on 3858 samples
Epoch 1/100
15432/15432 [==============================] - 7s 446us/step - loss: 8.0079 - acc: 0.4999 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 2/100
15432/15432 [==============================] - 8s 507us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 3/100
15432/15432 [==============================] - 8s 494us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 4/100
15432/15432 [==============================] - 8s 529us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 5/100
15432/15432 [==============================] - 8s 529us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961
Epoch 6/100
15432/15432 [==============================] - 8s 523us/step - loss: 8.0120 - acc: 0.5002 - val_loss: 8.0774 - val_acc: 0.4961


In [4]:
from autokeras.image.image_supervised import ImageClassifier

Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.


In [61]:
x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.3, random_state=42)
#y_train = np.column_stack((y_train, 1-y_train))
#y_test = np.column_stack((y_test, 1-y_test))

In [6]:
clf = ImageClassifier(path="~/automodels/",verbose=True, augment=False)
clf.fit(x_train, y_train, time_limit= 30 * 60)
clf.final_fit(x_train, y_train, x_test, y_test, retrain=True)
y = clf.evaluate(x_test, y_test)
print(y)

Saving Directory: ~/automodels/
Preprocessing the images.
Preprocessing finished.


ValueError: x_train should at least has 2 dimensions.

In [10]:
x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.3, random_state=42)
train_data = np.column_stack((x_train,y_train))
test_data = np.column_stack((x_test,y_test))
#x_train = np.column_stack((x_train,0*x_train))
#x_test = np.column_stack((x_test,0*x_test))
#y_train = np.column_stack((y_train, 1-y_train))
#y_test = np.column_stack((y_test, 1-y_test))

In [10]:
x_train

array([[2137.,    0.],
       [ 171.,    0.],
       [ 795.,    0.],
       ...,
       [ 314.,    0.],
       [1682.,    0.],
       [2200.,    0.]])

In [11]:
x_test

array([[ 246.,    0.],
       [ 935.,    0.],
       [2408.,    0.],
       ...,
       [ 783.,    0.],
       [ 369.,    0.],
       [ 417.,    0.]])

In [31]:
clf = ak.MlpModule(path="~/automodels/",verbose=True, metric='accuracy', loss='binary_crossentropy')
clf.fit(x_train, y_train, time_limit= 30 * 60)
clf.final_fit(x_train, y_train, x_test, y_test, retrain=True)
y = clf.evaluate(x_test, y_test)
print(y)

Saving Directory: ~/automodels/


TypeError: fit() missing 2 required positional arguments: 'train_data' and 'test_data'

In [13]:
x_train.shape

(19290, 2)

In [19]:
y_train.shape

(19290,)

In [15]:
x_test.shape

(8268, 2)

In [20]:
y_test.shape

(8268,)

In [1]:
import autokeras as ak

Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.


In [23]:
dir(ak)

['CnnModule',
 'ImageClassifier',
 'ImageRegressor',
 'MlpModule',
 'PortableImageSupervised',
 'TextClassifier',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'backend',
 'bayesian',
 'constant',
 'custom_queue',
 'image',
 'net_module',
 'net_transformer',
 'nn',
 'preprocessor',
 'search',
 'supervised',
 'text',
 'utils']

In [25]:
dir(ak.supervised)

['ABC',
 'Backend',
 'BayesianSearcher',
 'CnnModule',
 'Constant',
 'DeepTaskSupervised',
 'PortableDeepSupervised',
 'SearchSupervised',
 'SingleModelSupervised',
 'Supervised',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'abstractmethod',
 'ensure_dir',
 'os',
 'pickle_from_file',
 'pickle_to_file',
 'rand_temp_folder_generator',
 'train',
 'train_test_split',
 'validate_xy']

In [26]:
dir(ak.supervised.ABC)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '_abc_impl']

In [28]:
dir(ak.MlpModule)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'best_model',
 'final_fit',
 'fit',
 'predict']

In [32]:
import inspect
lines = inspect.getsource(ak.MlpModule)

In [33]:
lines

'class MlpModule(NetworkModule):\n    """ Class to create an MLP module."""\n\n    def __init__(self, loss, metric, searcher_args=None, path=None, verbose=False):\n        super(MlpModule, self).__init__(loss, metric, searcher_args, path, verbose, skip_conn=False)\n        self.generators.extend([MlpGenerator] * 2)\n'

In [34]:
lines.split("\n")

['class MlpModule(NetworkModule):',
 '    """ Class to create an MLP module."""',
 '',
 '    def __init__(self, loss, metric, searcher_args=None, path=None, verbose=False):',
 '        super(MlpModule, self).__init__(loss, metric, searcher_args, path, verbose, skip_conn=False)',
 '        self.generators.extend([MlpGenerator] * 2)',
 '']

In [35]:
dir(clf)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'best_model',
 'final_fit',
 'fit',
 'generators',
 'loss',
 'metric',
 'path',
 'predict',
 'search_type',
 'searcher',
 'searcher_args',
 'skip_conn',
 'verbose']

In [36]:
dir(clf.fit)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__func__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [37]:
lines = inspect.getsource(clf.fit)

In [39]:
lines.split("\n")

['    def fit(self, n_output_node, input_shape, train_data, test_data, time_limit=24 * 60 * 60):',
 '        """ Search the best network.',
 '',
 '        Args:',
 '            n_output_node: A integer value represent the number of output node in the final layer.',
 '            input_shape: A tuple to express the shape of every train entry. For example,',
 '                MNIST dataset would be (28,28,1).',
 '            train_data: A PyTorch DataLoader instance representing the training data.',
 '            test_data: A PyTorch DataLoader instance representing the testing data.',
 '            time_limit: A integer value represents the time limit on searching for models.',
 '        """',
 '        # Create the searcher and save on disk',
 '',
 '        if not self.searcher:',
 '            input_shape = input_shape[1:]',
 "            self.searcher_args['n_output_node'] = n_output_node",
 "            self.searcher_args['input_shape'] = input_shape",
 "            self.searcher_ar

In [2]:
import torch

In [3]:
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, utils

In [7]:
dataset = np.column_stack((data, labels))

In [8]:
data_torch = torch.from_numpy(dataset)

In [9]:
data_torch

tensor([[2.3800e+02, 0.0000e+00],
        [2.7900e+02, 0.0000e+00],
        [1.8000e+02, 0.0000e+00],
        ...,
        [1.6590e+03, 1.0000e+00],
        [1.3760e+03, 1.0000e+00],
        [1.3760e+03, 1.0000e+00]], dtype=torch.float64)

In [42]:
class ToTensor(object):
    """Convert ndarrays in sample to Tensors."""

    def __call__(self, data, labels):
        return {'image': torch.from_numpy(data),
                'landmarks': torch.from_numpy(labels)}

In [49]:
np.save("dataset.pickle", dataset, allow_pickle=True)

In [51]:
x,y = torch.load("dataset.pickle.npy")

UnpicklingError: STACK_GLOBAL requires str

In [53]:
import torch
import numpy as np
import torch.utils.data as utils

my_x = x_train # a list of numpy arrays
my_y = y_train # another list of numpy arrays (targets)

tensor_x = torch.stack([torch.Tensor(i) for i in my_x]) # transform to torch tensors
tensor_y = torch.stack([torch.Tensor(i) for i in my_y])

my_dataset = utils.TensorDataset(tensor_x,tensor_y) # create your datset
my_dataloader = utils.DataLoader(my_dataset) # create your dataloader

TypeError: new(): data must be a sequence (got numpy.float64)

In [58]:
y_train.tolist()

[1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0

In [64]:
import torch
import numpy as np
import torch.utils.data as utils

my_x = [x_train] # a list of numpy arrays
my_y = [y_train] # another list of numpy arrays (targets)

tensor_x = torch.stack([torch.Tensor(i) for i in my_x]) # transform to torch tensors
tensor_y = torch.stack([torch.Tensor(i) for i in my_y])

my_dataset = utils.TensorDataset(tensor_x,tensor_y) # create your datset
my_dataloader = utils.DataLoader(my_dataset) # create your dataloader

In [65]:
my_dataset

In [66]:
my_dataloader

In [13]:
clf = ak.MlpModule(path="~/automodels/",verbose=True, metric='accuracy', loss='binary_crossentropy')
clf.fit(train_data = train_data, test_data=test_data, time_limit= 30 * 60, input_shape = (1), n_output_node=1)
clf.final_fit(train_data = train_data, test_data=test_data, retrain=True)
y = clf.evaluate(x_test, y_test)
print(y)

Saving Directory: ~/automodels/


TypeError: 'int' object is not subscriptable

In [15]:
from autokeras import MlpModule
#from autokeras import classification_loss
from autokeras import Accuracy
from autokeras import OneHotEncoder
from autokeras import DataTransformerMlp

ImportError: cannot import name 'Accuracy' from 'autokeras' (/home/brandon/anaconda3/lib/python3.7/site-packages/autokeras/__init__.py)

In [18]:
ak.classification_loss()

AttributeError: module 'autokeras' has no attribute 'classification_loss'